spring.application.name=smart-appointment-system
spring.datasource.url=jdbc:postgresql://localhost:5433/smart_appointment_db
spring.datasource.username=postgres
spring.datasource.password=Punekar#123
spring.jpa.hibernate.ddl-auto=update
#query dikhega console me
spring.jpa.show-sql=true
#yah bas beautification karta hai sql query ka
spring.jpa.properties.hibernate.format_sql=true
# yah dialect bs batata hai ki we are about to use PostgreSql so give query according to their rule
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



